name: C/C++ CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: configure
      run: |
         sudo apt-get update
         sudo apt-get install cmake g++ gdb git libsdl2-dev zlib1g-dev patchelf
    - name: make
      run: ./build
    - name: ls
      run: ls
    - name: ls
      run: ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: ./
    - name: ls
      run: ls
